
  davinci_stereo_proc: {P1: 200.0, P2: 400.0, correlation_window_size: 125, disp12MaxDiff: 0,
    disparity_range: 64, fullDP: false, min_disparity: -98, prefilter_cap: 31, prefilter_size: 9,
    speckle_range: 4, speckle_size: 100, stereo_algorithm: 0, texture_threshold: 10,
    uniqueness_ratio: 15.0}
